import os
import glob
import cv2
import numpy as np
from PIL import Image
from tqdm import tqdm

# --- Configurations ---
INPUT_MASK_DIR = r"/content/drive/MyDrive/solar_PV/data/US/masks_full/"
OUTPUT_LABEL_DIR = r"/content/drive/MyDrive/solar_PV/data/US/labels_restored/"

# The pixel value representing the background (usually 0 or 255)
BACKGROUND_INDEX = 0

# Minimum area (in pixels) a polygon must have to be saved. 
# Useful for filtering out 1-pixel noise generated by model predictions.
MIN_AREA_PIXELS = 0 

# Tolerance for polygon approximation. 
# Higher = fewer points (smaller txt file), Lower = more precise following of pixel edges.
# 1.0 to 2.0 is usually a good sweet spot for masks.
APPROX_EPSILON = 1.0 / 5


def mask_to_yolo(mask_dir, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    
    # Find all PNGs in the directory
    mask_files = glob.glob(os.path.join(mask_dir, "*.png"))
    
    for mask_path in tqdm(mask_files, desc="Converting Masks to YOLO"):
        filename = os.path.basename(mask_path)
        image_id = os.path.splitext(filename)[0]
        
        # 1. Load mask using PIL to ensure proper 1-channel grayscale reading, then convert to NumPy
        mask = np.array(Image.open(mask_path))
        h, w = mask.shape[:2]
        
        # Get all unique classes in this mask, excluding the background
        unique_classes = np.unique(mask)
        classes_present = [c for c in unique_classes if c != BACKGROUND_INDEX]
        
        yolo_lines = []
        
        # 2. Iterate through each class present in the image
        for class_id in classes_present:
            # Create a binary mask for ONLY this specific class
            binary_mask = np.where(mask == class_id, 255, 0).astype(np.uint8)
            
            # 3. Find contours (boundaries)
            # RETR_EXTERNAL ignores holes inside the polygon (YOLO doesn't handle holes well)
            # CHAIN_APPROX_SIMPLE compresses straight horizontal/vertical lines
            contours, _ = cv2.findContours(binary_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            
            for contour in contours:
                # Filter out tiny noise artifacts
                if cv2.contourArea(contour) < MIN_AREA_PIXELS:
                    continue
                
                # Optional: Smooth the contour to reduce the number of points
                if APPROX_EPSILON > 0:
                    contour = cv2.approxPolyDP(contour, APPROX_EPSILON, closed=True)
                
                # YOLO needs at least 3 points (triangle) to make a valid polygon
                if len(contour) < 3:
                    continue
                
                # Flatten the contour array from (N, 1, 2) to (N, 2)
                contour = contour.reshape(-1, 2)
                
                # 4. Normalize coordinates to 0.0 - 1.0
                norm_coords = contour.astype(np.float64)
                norm_coords[:, 0] = norm_coords[:, 0] / w
                norm_coords[:, 1] = norm_coords[:, 1] / h
                
                # Clamp values strictly between 0 and 1 just in case
                norm_coords = np.clip(norm_coords, 0.0, 1.0)
                
                # 5. Format to YOLO string: "class_id x1 y1 x2 y2 ..."
                coords_str = " ".join([f"{x:.6f} {y:.6f}" for x, y in norm_coords])
                yolo_lines.append(f"{class_id} {coords_str}")
                
        # 6. Save to .txt file (even if empty, to tell YOLO there are no objects)
        txt_path = os.path.join(output_dir, f"{image_id}.txt")
        with open(txt_path, "w") as f:
            f.write("\n".join(yolo_lines))

if __name__ == "__main__":
    print("Starting reverse conversion...")
    mask_to_yolo(INPUT_MASK_DIR, OUTPUT_LABEL_DIR)
    print(f"Conversion complete! YOLO labels saved to {OUTPUT_LABEL_DIR}")
